apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName }}
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: dev-myhelmapp-stripprefix@kubernetescrd
spec:
  rules:
    - host: www.mpi.com
      http:
        paths:
          - path: /myhelmapp
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.appName }}
                port:
                  number: 80
